### ISSUE TITLE
No pins when scrolling around the world

### ISSUE THREAD

**Issue by teolag** [Vazerthon/funfunforum-usermap#12]
No big problem but the pins only show on the "first world map"
When you scroll around the world to east or west there are no pins.

**Comment by Vazerthon** [comment]
Good spot @teolag. Looks like Leaflet has a `{ worldCopyJump: true }` option that I can set. It's a little jumpy (as the name suggests) but it does mean you can't scroll to a point where no pins are shown.

In future I'll try using the geolocation api to set the initial map state which should further improve the UX around this.
